spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/PhoneShop13
    username: PhoneShop13
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
